# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  pingforce_config = release
  pingforce_test_config = release
endif
ifeq ($(config),debug)
  pingforce_config = debug
  pingforce_test_config = debug
endif

PROJECTS := pingforce pingforce_test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

pingforce:
ifneq (,$(pingforce_config))
	@echo "==== Building pingforce ($(pingforce_config)) ===="
	@${MAKE} --no-print-directory -C . -f pingforce.make config=$(pingforce_config)
endif

pingforce_test:
ifneq (,$(pingforce_test_config))
	@echo "==== Building pingforce_test ($(pingforce_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f pingforce_test.make config=$(pingforce_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f pingforce.make clean
	@${MAKE} --no-print-directory -C . -f pingforce_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pingforce"
	@echo "   pingforce_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"